# Test cubitpy.
cubitpy-testing:
    script:
        - "whoami"
        - "pwd"
        # Run tests.
        - "cd tests"
        - "python3 testing.py"
        - "./test_configurations.sh"
    variables:
        # Define variables for cubit and pre exodus.
        BACI_PRE_EXODUS: "/hdd/gitlab-runner/lib/baci-master/release/pre_exodus"
        CUBIT: "/rzhome/nas/compsim/public/opt/cubit-13.2"
    tags:
        - "imcs-all"
