# Test cubitpy.
cubitpy-testing:
    script:
        - "whoami"
        - "pwd"
        - export PYTHONPATH="${PYTHONPATH}:$(pwd)"
        # Run tests.
        - "cd tests"
        - "./test_configurations.sh"
    tags:
        - "imcs-all"
